package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_GROUP_ENTITY".
 */
public class ChatGroupEntity {

    private Long id;
    private String userName;
    private String nickName;
    private String type;
    private Integer receiveMode;
    private String avatar;
    private Long modified;
    private String tag;

    public ChatGroupEntity() {
    }

    public ChatGroupEntity(Long id) {
        this.id = id;
    }

    public ChatGroupEntity(Long id, String userName, String nickName, String type, Integer receiveMode, String avatar, Long modified, String tag) {
        this.id = id;
        this.userName = userName;
        this.nickName = nickName;
        this.type = type;
        this.receiveMode = receiveMode;
        this.avatar = avatar;
        this.modified = modified;
        this.tag = tag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getReceiveMode() {
        return receiveMode;
    }

    public void setReceiveMode(Integer receiveMode) {
        this.receiveMode = receiveMode;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Long getModified() {
        return modified;
    }

    public void setModified(Long modified) {
        this.modified = modified;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

}
