package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT_USER".
 */
public class ContactUser {

    private Long id;
    private String userId;
    private String updateTime;
    private String userName;
    private String departId;

    public ContactUser() {
    }

    public ContactUser(Long id) {
        this.id = id;
    }

    public ContactUser(Long id, String userId, String updateTime, String userName, String departId) {
        this.id = id;
        this.userId = userId;
        this.updateTime = updateTime;
        this.userName = userName;
        this.departId = departId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getDepartId() {
        return departId;
    }

    public void setDepartId(String departId) {
        this.departId = departId;
    }

}
