package mintcode.com.workhub_im.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import mintcode.com.workhub_im.db.SessionItemDao;
import mintcode.com.workhub_im.db.MessageItemDao;
import mintcode.com.workhub_im.db.DepartmentEntityDao;
import mintcode.com.workhub_im.db.GroupInfoDao;
import mintcode.com.workhub_im.db.ContactUserDao;
import mintcode.com.workhub_im.db.KeyValueDao;
import mintcode.com.workhub_im.db.UserDetailEntityDao;
import mintcode.com.workhub_im.db.MessageIdDao;
import mintcode.com.workhub_im.db.FriendEntityDao;
import mintcode.com.workhub_im.db.ChatGroupEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        SessionItemDao.createTable(db, ifNotExists);
        MessageItemDao.createTable(db, ifNotExists);
        DepartmentEntityDao.createTable(db, ifNotExists);
        GroupInfoDao.createTable(db, ifNotExists);
        ContactUserDao.createTable(db, ifNotExists);
        KeyValueDao.createTable(db, ifNotExists);
        UserDetailEntityDao.createTable(db, ifNotExists);
        MessageIdDao.createTable(db, ifNotExists);
        FriendEntityDao.createTable(db, ifNotExists);
        ChatGroupEntityDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        SessionItemDao.dropTable(db, ifExists);
        MessageItemDao.dropTable(db, ifExists);
        DepartmentEntityDao.dropTable(db, ifExists);
        GroupInfoDao.dropTable(db, ifExists);
        ContactUserDao.dropTable(db, ifExists);
        KeyValueDao.dropTable(db, ifExists);
        UserDetailEntityDao.dropTable(db, ifExists);
        MessageIdDao.dropTable(db, ifExists);
        FriendEntityDao.dropTable(db, ifExists);
        ChatGroupEntityDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SessionItemDao.class);
        registerDaoClass(MessageItemDao.class);
        registerDaoClass(DepartmentEntityDao.class);
        registerDaoClass(GroupInfoDao.class);
        registerDaoClass(ContactUserDao.class);
        registerDaoClass(KeyValueDao.class);
        registerDaoClass(UserDetailEntityDao.class);
        registerDaoClass(MessageIdDao.class);
        registerDaoClass(FriendEntityDao.class);
        registerDaoClass(ChatGroupEntityDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
