package mintcode.com.workhub_im.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import mintcode.com.workhub_im.db.SessionItem;
import mintcode.com.workhub_im.db.MessageItem;

import mintcode.com.workhub_im.db.SessionItemDao;
import mintcode.com.workhub_im.db.MessageItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sessionItemDaoConfig;
    private final DaoConfig messageItemDaoConfig;

    private final SessionItemDao sessionItemDao;
    private final MessageItemDao messageItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sessionItemDaoConfig = daoConfigMap.get(SessionItemDao.class).clone();
        sessionItemDaoConfig.initIdentityScope(type);

        messageItemDaoConfig = daoConfigMap.get(MessageItemDao.class).clone();
        messageItemDaoConfig.initIdentityScope(type);

        sessionItemDao = new SessionItemDao(sessionItemDaoConfig, this);
        messageItemDao = new MessageItemDao(messageItemDaoConfig, this);

        registerDao(SessionItem.class, sessionItemDao);
        registerDao(MessageItem.class, messageItemDao);
    }
    
    public void clear() {
        sessionItemDaoConfig.getIdentityScope().clear();
        messageItemDaoConfig.getIdentityScope().clear();
    }

    public SessionItemDao getSessionItemDao() {
        return sessionItemDao;
    }

    public MessageItemDao getMessageItemDao() {
        return messageItemDao;
    }

}
