package mintcode.com.workhub_im.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import mintcode.com.workhub_im.db.SessionItem;
import mintcode.com.workhub_im.db.MessageItem;
import mintcode.com.workhub_im.db.DepartmentEntity;
import mintcode.com.workhub_im.db.GroupInfo;
import mintcode.com.workhub_im.db.ContactUser;
import mintcode.com.workhub_im.db.KeyValue;
import mintcode.com.workhub_im.db.UserDetailEntity;
import mintcode.com.workhub_im.db.MessageId;
import mintcode.com.workhub_im.db.FriendEntity;
import mintcode.com.workhub_im.db.ChatGroupEntity;

import mintcode.com.workhub_im.db.SessionItemDao;
import mintcode.com.workhub_im.db.MessageItemDao;
import mintcode.com.workhub_im.db.DepartmentEntityDao;
import mintcode.com.workhub_im.db.GroupInfoDao;
import mintcode.com.workhub_im.db.ContactUserDao;
import mintcode.com.workhub_im.db.KeyValueDao;
import mintcode.com.workhub_im.db.UserDetailEntityDao;
import mintcode.com.workhub_im.db.MessageIdDao;
import mintcode.com.workhub_im.db.FriendEntityDao;
import mintcode.com.workhub_im.db.ChatGroupEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sessionItemDaoConfig;
    private final DaoConfig messageItemDaoConfig;
    private final DaoConfig departmentEntityDaoConfig;
    private final DaoConfig groupInfoDaoConfig;
    private final DaoConfig contactUserDaoConfig;
    private final DaoConfig keyValueDaoConfig;
    private final DaoConfig userDetailEntityDaoConfig;
    private final DaoConfig messageIdDaoConfig;
    private final DaoConfig friendEntityDaoConfig;
    private final DaoConfig chatGroupEntityDaoConfig;

    private final SessionItemDao sessionItemDao;
    private final MessageItemDao messageItemDao;
    private final DepartmentEntityDao departmentEntityDao;
    private final GroupInfoDao groupInfoDao;
    private final ContactUserDao contactUserDao;
    private final KeyValueDao keyValueDao;
    private final UserDetailEntityDao userDetailEntityDao;
    private final MessageIdDao messageIdDao;
    private final FriendEntityDao friendEntityDao;
    private final ChatGroupEntityDao chatGroupEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sessionItemDaoConfig = daoConfigMap.get(SessionItemDao.class).clone();
        sessionItemDaoConfig.initIdentityScope(type);

        messageItemDaoConfig = daoConfigMap.get(MessageItemDao.class).clone();
        messageItemDaoConfig.initIdentityScope(type);

        departmentEntityDaoConfig = daoConfigMap.get(DepartmentEntityDao.class).clone();
        departmentEntityDaoConfig.initIdentityScope(type);

        groupInfoDaoConfig = daoConfigMap.get(GroupInfoDao.class).clone();
        groupInfoDaoConfig.initIdentityScope(type);

        contactUserDaoConfig = daoConfigMap.get(ContactUserDao.class).clone();
        contactUserDaoConfig.initIdentityScope(type);

        keyValueDaoConfig = daoConfigMap.get(KeyValueDao.class).clone();
        keyValueDaoConfig.initIdentityScope(type);

        userDetailEntityDaoConfig = daoConfigMap.get(UserDetailEntityDao.class).clone();
        userDetailEntityDaoConfig.initIdentityScope(type);

        messageIdDaoConfig = daoConfigMap.get(MessageIdDao.class).clone();
        messageIdDaoConfig.initIdentityScope(type);

        friendEntityDaoConfig = daoConfigMap.get(FriendEntityDao.class).clone();
        friendEntityDaoConfig.initIdentityScope(type);

        chatGroupEntityDaoConfig = daoConfigMap.get(ChatGroupEntityDao.class).clone();
        chatGroupEntityDaoConfig.initIdentityScope(type);

        sessionItemDao = new SessionItemDao(sessionItemDaoConfig, this);
        messageItemDao = new MessageItemDao(messageItemDaoConfig, this);
        departmentEntityDao = new DepartmentEntityDao(departmentEntityDaoConfig, this);
        groupInfoDao = new GroupInfoDao(groupInfoDaoConfig, this);
        contactUserDao = new ContactUserDao(contactUserDaoConfig, this);
        keyValueDao = new KeyValueDao(keyValueDaoConfig, this);
        userDetailEntityDao = new UserDetailEntityDao(userDetailEntityDaoConfig, this);
        messageIdDao = new MessageIdDao(messageIdDaoConfig, this);
        friendEntityDao = new FriendEntityDao(friendEntityDaoConfig, this);
        chatGroupEntityDao = new ChatGroupEntityDao(chatGroupEntityDaoConfig, this);

        registerDao(SessionItem.class, sessionItemDao);
        registerDao(MessageItem.class, messageItemDao);
        registerDao(DepartmentEntity.class, departmentEntityDao);
        registerDao(GroupInfo.class, groupInfoDao);
        registerDao(ContactUser.class, contactUserDao);
        registerDao(KeyValue.class, keyValueDao);
        registerDao(UserDetailEntity.class, userDetailEntityDao);
        registerDao(MessageId.class, messageIdDao);
        registerDao(FriendEntity.class, friendEntityDao);
        registerDao(ChatGroupEntity.class, chatGroupEntityDao);
    }
    
    public void clear() {
        sessionItemDaoConfig.getIdentityScope().clear();
        messageItemDaoConfig.getIdentityScope().clear();
        departmentEntityDaoConfig.getIdentityScope().clear();
        groupInfoDaoConfig.getIdentityScope().clear();
        contactUserDaoConfig.getIdentityScope().clear();
        keyValueDaoConfig.getIdentityScope().clear();
        userDetailEntityDaoConfig.getIdentityScope().clear();
        messageIdDaoConfig.getIdentityScope().clear();
        friendEntityDaoConfig.getIdentityScope().clear();
        chatGroupEntityDaoConfig.getIdentityScope().clear();
    }

    public SessionItemDao getSessionItemDao() {
        return sessionItemDao;
    }

    public MessageItemDao getMessageItemDao() {
        return messageItemDao;
    }

    public DepartmentEntityDao getDepartmentEntityDao() {
        return departmentEntityDao;
    }

    public GroupInfoDao getGroupInfoDao() {
        return groupInfoDao;
    }

    public ContactUserDao getContactUserDao() {
        return contactUserDao;
    }

    public KeyValueDao getKeyValueDao() {
        return keyValueDao;
    }

    public UserDetailEntityDao getUserDetailEntityDao() {
        return userDetailEntityDao;
    }

    public MessageIdDao getMessageIdDao() {
        return messageIdDao;
    }

    public FriendEntityDao getFriendEntityDao() {
        return friendEntityDao;
    }

    public ChatGroupEntityDao getChatGroupEntityDao() {
        return chatGroupEntityDao;
    }

}
