package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FRIEND_ENTITY".
 */
public class FriendEntity {

    private Long id;
    private String appName;
    private String userName;
    private String relationName;
    private String remark;
    private String tag;
    private Integer relationGroupId;
    private Long createDate;
    private String isPass;
    private String nickName;
    private String relationAvatar;
    private Long relationModified;
    private String mobile;
    private String imNumber;

    public FriendEntity() {
    }

    public FriendEntity(Long id) {
        this.id = id;
    }

    public FriendEntity(Long id, String appName, String userName, String relationName, String remark, String tag, Integer relationGroupId, Long createDate, String isPass, String nickName, String relationAvatar, Long relationModified, String mobile, String imNumber) {
        this.id = id;
        this.appName = appName;
        this.userName = userName;
        this.relationName = relationName;
        this.remark = remark;
        this.tag = tag;
        this.relationGroupId = relationGroupId;
        this.createDate = createDate;
        this.isPass = isPass;
        this.nickName = nickName;
        this.relationAvatar = relationAvatar;
        this.relationModified = relationModified;
        this.mobile = mobile;
        this.imNumber = imNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getRelationName() {
        return relationName;
    }

    public void setRelationName(String relationName) {
        this.relationName = relationName;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Integer getRelationGroupId() {
        return relationGroupId;
    }

    public void setRelationGroupId(Integer relationGroupId) {
        this.relationGroupId = relationGroupId;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public String getIsPass() {
        return isPass;
    }

    public void setIsPass(String isPass) {
        this.isPass = isPass;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getRelationAvatar() {
        return relationAvatar;
    }

    public void setRelationAvatar(String relationAvatar) {
        this.relationAvatar = relationAvatar;
    }

    public Long getRelationModified() {
        return relationModified;
    }

    public void setRelationModified(Long relationModified) {
        this.relationModified = relationModified;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getImNumber() {
        return imNumber;
    }

    public void setImNumber(String imNumber) {
        this.imNumber = imNumber;
    }

}
