package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP_INFO".
 */
public class GroupInfo {

    private Long id;
    private String userName;
    private String nickName;
    private String type;
    private String avatar;
    private Long modified;

    public GroupInfo() {
    }

    public GroupInfo(Long id) {
        this.id = id;
    }

    public GroupInfo(Long id, String userName, String nickName, String type, String avatar, Long modified) {
        this.id = id;
        this.userName = userName;
        this.nickName = nickName;
        this.type = type;
        this.avatar = avatar;
        this.modified = modified;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Long getModified() {
        return modified;
    }

    public void setModified(Long modified) {
        this.modified = modified;
    }

}
