package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_ITEM".
 */
public class MessageItem {

    private Long id;
    private String appName;
    private String userName;
    private Long modified;
    private String nickName;
    private Long msgId;
    private String from;
    private String to;
    private String info;
    private String content;
    private Long clientMsgId;
    private Long createDate;
    private String type;
    private Integer cmd;
    private Integer sent;
    private String timeText;
    private String fileName;
    private String fileSize;
    private String isRead;
    private Integer actionSend;
    private Integer isMarkPoint;
    private Integer isResp;
    private Long send_time;
    private String toNickName;
    private String percent;

    public MessageItem() {
    }

    public MessageItem(Long id) {
        this.id = id;
    }

    public MessageItem(Long id, String appName, String userName, Long modified, String nickName, Long msgId, String from, String to, String info, String content, Long clientMsgId, Long createDate, String type, Integer cmd, Integer sent, String timeText, String fileName, String fileSize, String isRead, Integer actionSend, Integer isMarkPoint, Integer isResp, Long send_time, String toNickName, String percent) {
        this.id = id;
        this.appName = appName;
        this.userName = userName;
        this.modified = modified;
        this.nickName = nickName;
        this.msgId = msgId;
        this.from = from;
        this.to = to;
        this.info = info;
        this.content = content;
        this.clientMsgId = clientMsgId;
        this.createDate = createDate;
        this.type = type;
        this.cmd = cmd;
        this.sent = sent;
        this.timeText = timeText;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.isRead = isRead;
        this.actionSend = actionSend;
        this.isMarkPoint = isMarkPoint;
        this.isResp = isResp;
        this.send_time = send_time;
        this.toNickName = toNickName;
        this.percent = percent;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Long getModified() {
        return modified;
    }

    public void setModified(Long modified) {
        this.modified = modified;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Long getMsgId() {
        return msgId;
    }

    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getClientMsgId() {
        return clientMsgId;
    }

    public void setClientMsgId(Long clientMsgId) {
        this.clientMsgId = clientMsgId;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getCmd() {
        return cmd;
    }

    public void setCmd(Integer cmd) {
        this.cmd = cmd;
    }

    public Integer getSent() {
        return sent;
    }

    public void setSent(Integer sent) {
        this.sent = sent;
    }

    public String getTimeText() {
        return timeText;
    }

    public void setTimeText(String timeText) {
        this.timeText = timeText;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileSize() {
        return fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getIsRead() {
        return isRead;
    }

    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }

    public Integer getActionSend() {
        return actionSend;
    }

    public void setActionSend(Integer actionSend) {
        this.actionSend = actionSend;
    }

    public Integer getIsMarkPoint() {
        return isMarkPoint;
    }

    public void setIsMarkPoint(Integer isMarkPoint) {
        this.isMarkPoint = isMarkPoint;
    }

    public Integer getIsResp() {
        return isResp;
    }

    public void setIsResp(Integer isResp) {
        this.isResp = isResp;
    }

    public Long getSend_time() {
        return send_time;
    }

    public void setSend_time(Long send_time) {
        this.send_time = send_time;
    }

    public String getToNickName() {
        return toNickName;
    }

    public void setToNickName(String toNickName) {
        this.toNickName = toNickName;
    }

    public String getPercent() {
        return percent;
    }

    public void setPercent(String percent) {
        this.percent = percent;
    }

}
