package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_ITEM".
 */
public class MessageItem {

    private Long id;
    private String appName;
    private String userName;
    private Long modified;
    private String nickName;
    private Long msgId;
    private String fromLoginName;
    private String toLoginName;
    private String info;
    private String content;
    private Long clientMsgId;
    private Long createDate;
    private String type;
    private Integer cmd;
    private String timeText;
    private String fileName;
    private String fileSize;
    private String isRead;
    private Integer actionSend;
    private Integer isMarkPoint;
    private Integer isResp;
    private Long send_time;
    private String toNickName;
    private String percent;

    public MessageItem() {
    }

    public MessageItem(Long id) {
        this.id = id;
    }

    public MessageItem(Long id, String appName, String userName, Long modified, String nickName, Long msgId, String fromLoginName, String toLoginName, String info, String content, Long clientMsgId, Long createDate, String type, Integer cmd, String timeText, String fileName, String fileSize, String isRead, Integer actionSend, Integer isMarkPoint, Integer isResp, Long send_time, String toNickName, String percent) {
        this.id = id;
        this.appName = appName;
        this.userName = userName;
        this.modified = modified;
        this.nickName = nickName;
        this.msgId = msgId;
        this.fromLoginName = fromLoginName;
        this.toLoginName = toLoginName;
        this.info = info;
        this.content = content;
        this.clientMsgId = clientMsgId;
        this.createDate = createDate;
        this.type = type;
        this.cmd = cmd;
        this.timeText = timeText;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.isRead = isRead;
        this.actionSend = actionSend;
        this.isMarkPoint = isMarkPoint;
        this.isResp = isResp;
        this.send_time = send_time;
        this.toNickName = toNickName;
        this.percent = percent;
    }

    private MessageItem(Builder builder) {
        setId(builder.id);
        setAppName(builder.appName);
        setUserName(builder.userName);
        setModified(builder.modified);
        setNickName(builder.nickName);
        setMsgId(builder.msgId);
        setFromLoginName(builder.fromLoginName);
        setToLoginName(builder.toLoginName);
        setInfo(builder.info);
        setContent(builder.content);
        setClientMsgId(builder.clientMsgId);
        setCreateDate(builder.createDate);
        setType(builder.type);
        setCmd(builder.cmd);
        setTimeText(builder.timeText);
        setFileName(builder.fileName);
        setFileSize(builder.fileSize);
        setIsRead(builder.isRead);
        setActionSend(builder.actionSend);
        setIsMarkPoint(builder.isMarkPoint);
        setIsResp(builder.isResp);
        setSend_time(builder.send_time);
        setToNickName(builder.toNickName);
        setPercent(builder.percent);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Long getModified() {
        return modified;
    }

    public void setModified(Long modified) {
        this.modified = modified;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Long getMsgId() {
        return msgId;
    }

    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    public String getFromLoginName() {
        return fromLoginName;
    }

    public void setFromLoginName(String fromLoginName) {
        this.fromLoginName = fromLoginName;
    }

    public String getToLoginName() {
        return toLoginName;
    }

    public void setToLoginName(String toLoginName) {
        this.toLoginName = toLoginName;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getClientMsgId() {
        return clientMsgId;
    }

    public void setClientMsgId(Long clientMsgId) {
        this.clientMsgId = clientMsgId;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getCmd() {
        return cmd;
    }

    public void setCmd(Integer cmd) {
        this.cmd = cmd;
    }

    public String getTimeText() {
        return timeText;
    }

    public void setTimeText(String timeText) {
        this.timeText = timeText;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileSize() {
        return fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getIsRead() {
        return isRead;
    }

    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }

    public Integer getActionSend() {
        return actionSend;
    }

    public void setActionSend(Integer actionSend) {
        this.actionSend = actionSend;
    }

    public Integer getIsMarkPoint() {
        return isMarkPoint;
    }

    public void setIsMarkPoint(Integer isMarkPoint) {
        this.isMarkPoint = isMarkPoint;
    }

    public Integer getIsResp() {
        return isResp;
    }

    public void setIsResp(Integer isResp) {
        this.isResp = isResp;
    }

    public Long getSend_time() {
        return send_time;
    }

    public void setSend_time(Long send_time) {
        this.send_time = send_time;
    }

    public String getToNickName() {
        return toNickName;
    }

    public void setToNickName(String toNickName) {
        this.toNickName = toNickName;
    }

    public String getPercent() {
        return percent;
    }

    public void setPercent(String percent) {
        this.percent = percent;
    }


    public static final class Builder {
        private Long id;
        private String appName;
        private String userName;
        private Long modified;
        private String nickName;
        private Long msgId;
        private String fromLoginName;
        private String toLoginName;
        private String info;
        private String content;
        private Long clientMsgId;
        private Long createDate;
        private String type;
        private Integer cmd;
        private String timeText;
        private String fileName;
        private String fileSize;
        private String isRead;
        private Integer actionSend;
        private Integer isMarkPoint;
        private Integer isResp;
        private Long send_time;
        private String toNickName;
        private String percent;

        public Builder() {
        }

        public Builder id(Long val) {
            id = val;
            return this;
        }

        public Builder appName(String val) {
            appName = val;
            return this;
        }

        public Builder userName(String val) {
            userName = val;
            return this;
        }

        public Builder modified(Long val) {
            modified = val;
            return this;
        }

        public Builder nickName(String val) {
            nickName = val;
            return this;
        }

        public Builder msgId(Long val) {
            msgId = val;
            return this;
        }

        public Builder fromLoginName(String val) {
            fromLoginName = val;
            return this;
        }

        public Builder toLoginName(String val) {
            toLoginName = val;
            return this;
        }

        public Builder info(String val) {
            info = val;
            return this;
        }

        public Builder content(String val) {
            content = val;
            return this;
        }

        public Builder clientMsgId(Long val) {
            clientMsgId = val;
            return this;
        }

        public Builder createDate(Long val) {
            createDate = val;
            return this;
        }

        public Builder type(String val) {
            type = val;
            return this;
        }

        public Builder cmd(Integer val) {
            cmd = val;
            return this;
        }

        public Builder timeText(String val) {
            timeText = val;
            return this;
        }

        public Builder fileName(String val) {
            fileName = val;
            return this;
        }

        public Builder fileSize(String val) {
            fileSize = val;
            return this;
        }

        public Builder isRead(String val) {
            isRead = val;
            return this;
        }

        public Builder actionSend(Integer val) {
            actionSend = val;
            return this;
        }

        public Builder isMarkPoint(Integer val) {
            isMarkPoint = val;
            return this;
        }

        public Builder isResp(Integer val) {
            isResp = val;
            return this;
        }

        public Builder send_time(Long val) {
            send_time = val;
            return this;
        }

        public Builder toNickName(String val) {
            toNickName = val;
            return this;
        }

        public Builder percent(String val) {
            percent = val;
            return this;
        }

        public MessageItem build() {
            return new MessageItem(this);
        }
    }
}
