package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SESSION_ITEM".
 */
public class SessionItem {

    private Long id;
    private String userName;
    private String nickName;
    private String oppositeName;
    private String content;
    private Long time;
    private String info;
    private Integer unread;
    private Integer chatRoom;
    private Integer sort;
    private Integer recieve;
    private Integer drafts;
    private Long clientMsgId;
    private Long sessionTime;

    public SessionItem() {
    }

    public SessionItem(Long id) {
        this.id = id;
    }

    public SessionItem(Long id, String userName, String nickName, String oppositeName, String content, Long time, String info, Integer unread, Integer chatRoom, Integer sort, Integer recieve, Integer drafts, Long clientMsgId, Long sessionTime) {
        this.id = id;
        this.userName = userName;
        this.nickName = nickName;
        this.oppositeName = oppositeName;
        this.content = content;
        this.time = time;
        this.info = info;
        this.unread = unread;
        this.chatRoom = chatRoom;
        this.sort = sort;
        this.recieve = recieve;
        this.drafts = drafts;
        this.clientMsgId = clientMsgId;
        this.sessionTime = sessionTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getOppositeName() {
        return oppositeName;
    }

    public void setOppositeName(String oppositeName) {
        this.oppositeName = oppositeName;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public Integer getUnread() {
        return unread;
    }

    public void setUnread(Integer unread) {
        this.unread = unread;
    }

    public Integer getChatRoom() {
        return chatRoom;
    }

    public void setChatRoom(Integer chatRoom) {
        this.chatRoom = chatRoom;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getRecieve() {
        return recieve;
    }

    public void setRecieve(Integer recieve) {
        this.recieve = recieve;
    }

    public Integer getDrafts() {
        return drafts;
    }

    public void setDrafts(Integer drafts) {
        this.drafts = drafts;
    }

    public Long getClientMsgId() {
        return clientMsgId;
    }

    public void setClientMsgId(Long clientMsgId) {
        this.clientMsgId = clientMsgId;
    }

    public Long getSessionTime() {
        return sessionTime;
    }

    public void setSessionTime(Long sessionTime) {
        this.sessionTime = sessionTime;
    }

}
