package mintcode.com.workhub_im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_DETAIL_ENTITY".
 */
public class UserDetailEntity {

    private Long id;
    private String showId;
    private String name;
    private String trueName;
    private String trueNameC;
    private String mail;
    private String status;
    private String mobile;
    private String job;
    private String number;
    private String sort;
    private String lastLoginTime;
    private String lastLoginToken;
    private String isAdmin;
    private String cShowId;
    private String createUser;
    private String createTime;
    private String dName;
    private String deptId;
    private String parentShowId;
    private String pathName;
    private String hira;
    private String telephone;
    private String otherField;
    private Long launchrId;

    public UserDetailEntity() {
    }

    public UserDetailEntity(Long id) {
        this.id = id;
    }

    public UserDetailEntity(Long id, String showId, String name, String trueName, String trueNameC, String mail, String status, String mobile, String job, String number, String sort, String lastLoginTime, String lastLoginToken, String isAdmin, String cShowId, String createUser, String createTime, String dName, String deptId, String parentShowId, String pathName, String hira, String telephone, String otherField, Long launchrId) {
        this.id = id;
        this.showId = showId;
        this.name = name;
        this.trueName = trueName;
        this.trueNameC = trueNameC;
        this.mail = mail;
        this.status = status;
        this.mobile = mobile;
        this.job = job;
        this.number = number;
        this.sort = sort;
        this.lastLoginTime = lastLoginTime;
        this.lastLoginToken = lastLoginToken;
        this.isAdmin = isAdmin;
        this.cShowId = cShowId;
        this.createUser = createUser;
        this.createTime = createTime;
        this.dName = dName;
        this.deptId = deptId;
        this.parentShowId = parentShowId;
        this.pathName = pathName;
        this.hira = hira;
        this.telephone = telephone;
        this.otherField = otherField;
        this.launchrId = launchrId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShowId() {
        return showId;
    }

    public void setShowId(String showId) {
        this.showId = showId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTrueName() {
        return trueName;
    }

    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    public String getTrueNameC() {
        return trueNameC;
    }

    public void setTrueNameC(String trueNameC) {
        this.trueNameC = trueNameC;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public String getLastLoginToken() {
        return lastLoginToken;
    }

    public void setLastLoginToken(String lastLoginToken) {
        this.lastLoginToken = lastLoginToken;
    }

    public String getIsAdmin() {
        return isAdmin;
    }

    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin;
    }

    public String getCShowId() {
        return cShowId;
    }

    public void setCShowId(String cShowId) {
        this.cShowId = cShowId;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getDName() {
        return dName;
    }

    public void setDName(String dName) {
        this.dName = dName;
    }

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getParentShowId() {
        return parentShowId;
    }

    public void setParentShowId(String parentShowId) {
        this.parentShowId = parentShowId;
    }

    public String getPathName() {
        return pathName;
    }

    public void setPathName(String pathName) {
        this.pathName = pathName;
    }

    public String getHira() {
        return hira;
    }

    public void setHira(String hira) {
        this.hira = hira;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getOtherField() {
        return otherField;
    }

    public void setOtherField(String otherField) {
        this.otherField = otherField;
    }

    public Long getLaunchrId() {
        return launchrId;
    }

    public void setLaunchrId(Long launchrId) {
        this.launchrId = launchrId;
    }

}
