package com.mintcode.launchr.pojo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Entity mapped to table "RM_DATA".
 */
public class rmDataEntity {

    private String title;
    private Long start;
    private Long end;
    private Long deadline;
    private String id;
    private Float fee;
    private Integer isDeadlineAllday;
    private Integer isTimeslotAllday;
    private String backup;
    private String approvalShowID;
    private String approvalType;
    private String reason;
    private String status;
    private String content;

    public rmDataEntity() {
    }

    public String getContent() {
        return content;
    }
    @JsonProperty("content")
    public void setContent(String content) {
        this.content = content;
    }
    public String getTitle() {
        return title;
    }
    @JsonProperty("title")
    public void setTitle(String title) {
        this.title = title;
    }

    public Long getStart() {
        return start;
    }
    @JsonProperty("start")
    public void setStart(Long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }
    @JsonProperty("end")
    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getDeadline() {
        return deadline;
    }
    @JsonProperty("deadline")
    public void setDeadline(Long deadline) {
        this.deadline = deadline;
    }

    public String getId() {
        return id;
    }
    @JsonProperty("id")
    public void setId(String id) {
        this.id = id;
    }

    public Float getFee() {
        return fee;
    }
    @JsonProperty("fee")
    public void setFee(Float fee) {
        this.fee = fee;
    }

    public Integer getIsDeadlineAllday() {
        return isDeadlineAllday;
    }
    @JsonProperty("isDeadlineAllday")
    public void setIsDeadlineAllday(Integer isDeadlineAllday) {
        this.isDeadlineAllday = isDeadlineAllday;
    }

    public Integer getIsTimeslotAllday() {
        return isTimeslotAllday;
    }
    @JsonProperty("isTimeslotAllday")
    public void setIsTimeslotAllday(Integer isTimeslotAllday) {
        this.isTimeslotAllday = isTimeslotAllday;
    }

    public String getBackup() {
        return backup;
    }
    @JsonProperty("backup")
    public void setBackup(String backup) {
        this.backup = backup;
    }

    public String getApprovalShowID() {
        return approvalShowID;
    }
    @JsonProperty("approvalShowID")
    public void setApprovalShowID(String approvalShowID) {
        this.approvalShowID = approvalShowID;
    }

    public String getApprovalType() {
        return approvalType;
    }
    @JsonProperty("approvalType")
    public void setApprovalType(String approvalType) {
        this.approvalType = approvalType;
    }

    public String getReason() {
        return reason;
    }
    @JsonProperty("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return status;
    }
    @JsonProperty("status")
    public void setStatus(String status) {
        this.status = status;
    }

}
