package com.mintcode.launchr.pojo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK_DETAIL".
 */
public class TaskListEntity {

    private String showId;
    private String title;
    private long endTime;
    private long startTime;
    private int isEndTimeAllDay;
    private String userName;
    private String userTrueName;
    private String priority;
    private String type;
    private int isAnnex;
    private int isComment;
    private int level;
    private String parentTaskId;
    private String projectId;
    private String projectName;
    private int finishedTask;
    private int allTask;

    public TaskListEntity() {
    }

    public TaskListEntity(String showId, String title, long endTime, int isEndTimeAllDay, String userName, String userTrueName, String priority, String type, int isAnnex, int isComment, int level, String parentTaskId, String projectId, String projectName, int finishedTask, int allTask) {
        this.showId = showId;
        this.title = title;
        this.endTime = endTime;
        this.isEndTimeAllDay = isEndTimeAllDay;
        this.userName = userName;
        this.userTrueName = userTrueName;
        this.priority = priority;
        this.type = type;
        this.isAnnex = isAnnex;
        this.isComment = isComment;
        this.level = level;
        this.parentTaskId = parentTaskId;
        this.projectId = projectId;
        this.projectName = projectName;
        this.finishedTask = finishedTask;
        this.allTask = allTask;
    }


    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public String getShowId() {
        return showId;
    }

    public void setShowId(String showId) {
        this.showId = showId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    public int getIsEndTimeAllDay() {
        return isEndTimeAllDay;
    }

    public void setIsEndTimeAllDay(int isEndTimeAllDay) {
        this.isEndTimeAllDay = isEndTimeAllDay;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserTrueName() {
        return userTrueName;
    }

    public void setUserTrueName(String userTrueName) {
        this.userTrueName = userTrueName;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getIsAnnex() {
        return isAnnex;
    }

    public void setIsAnnex(int isAnnex) {
        this.isAnnex = isAnnex;
    }

    public int getIsComment() {
        return isComment;
    }

    public void setIsComment(int isComment) {
        this.isComment = isComment;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public String getParentTaskId() {
        return parentTaskId;
    }

    public void setParentTaskId(String parentTaskId) {
        this.parentTaskId = parentTaskId;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public int getFinishedTask() {
        return finishedTask;
    }

    public void setFinishedTask(int finishedTask) {
        this.finishedTask = finishedTask;
    }

    public int getAllTask() {
        return allTask;
    }

    public void setAllTask(int allTask) {
        this.allTask = allTask;
    }

}
